### ISSUE TITLE
K9 crashes when using a PGP key in Settings - Cryptography

### ISSUE THREAD

**Issue by CRtEurope** [scoute-dich/K9-MailClient#18] opened 2017-04-07 11:39 UTC
I have k-9 Mail and openkeychain installed on my Android 7.1.1. All keys have been successfully imported into openkeychain. Normally you can select a key for use in K-9 Mail when you go to settings - cryptography. 

### Actual behavior
When I open K-9 Mail and go to the settings - cryptography in order to tip the key for use then K-9 Mail immediately crashes. It happens all the time, so I cannot use encrytion in my emails.

### Environment
K-9 Mail version: 5.206

Android version: Nougat 7.1.1 Custom Rom: LineageOs

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by scoute-dich** [comment] 2017-04-18 14:10
duplicate of #7

**Closed by scoute-dich** 2017-04-18 14:10 UTC
